# Generated by Django 5.1.7 on 2025-03-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='analista',
        ),
    ]
