# Generated by Django 5.1.7 on 2025-05-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_remove_produtoinventario_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoinventario',
            name='status',
        ),
        
    ]
