# Generated by Django 5.1.7 on 2025-04-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_alter_chamado_arquivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='arquivos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
