# Generated by Django 5.1.7 on 2025-05-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_grupo_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo', models.CharField(choices=[('usuario', 'Usuário Comum'), ('analista', 'Analista')], default='usuario', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('deletado', models.BooleanField(default=False)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.cargo')),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.group')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.grupo')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.setor')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
