# Generated by Django 5.1.7 on 2025-05-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_setor_grupo'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='grupo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.grupo'),
        ),
    ]
