# Generated by Django 5.1.7 on 2025-05-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_grupo_usuario_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='grupo',
            new_name='grupos',
        ),
    ]
