# Generated by Django 5.1.7 on 2025-05-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_groups_remove_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acesso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
