# Generated by Django 5.1.7 on 2025-05-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_links_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='logo',
            field=models.CharField(blank=True, help_text='Nome do arquivo da imagem (ex: BMG.png)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='tipo',
            field=models.CharField(choices=[('sistema', 'Sistema'), ('banco', 'Banco')], max_length=20),
        ),
    ]
