# Generated by Django 5.1.7 on 2025-04-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores', to='users.area'),
        ),
    ]
