# Generated by Django 5.1.7 on 2025-05-18 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grupo_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='core.grupo'),
        ),
    ]
