# Generated by Django 5.1.7 on 2025-03-31 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_remove_chamado_analista'),
        ('usuarios', '0005_usuario_tipo_delete_analista'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.setor'),
            preserve_default=False,
        ),
    ]
