# Generated by Django 5.1.7 on 2025-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_chamado_analista'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='arquivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='solucao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
