# Generated by Django 5.1.7 on 2025-04-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_chamado_arquivos_chamado_comentarios_chamado_solucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='arquivos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
