# Generated by Django 5.1.7 on 2025-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_alter_chamado_arquivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='gravidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
