# Generated by Django 5.1.7 on 2025-04-14 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0014_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='chamados.chamado'),
        ),
    ]
