# Generated by Django 5.1.7 on 2025-05-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='tipo',
            field=models.CharField(default='sistema', max_length=20),
        ),
    ]
