# Generated by Django 5.1.7 on 2025-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analista',
            name='senha',
            field=models.CharField(default='senha123', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='senha123', max_length=15),
            preserve_default=False,
        ),
    ]
