# Generated by Django 5.1.7 on 2025-03-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_analista_senha_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analista',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
