# Generated by Django 5.1.7 on 2025-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_analista_senha_analista_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analista',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
