# Generated by Django 5.1.7 on 2025-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_analista_is_admin_usuario_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analista',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='analista_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='analista',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='analista_set', to='auth.permission'),
        ),
    ]
