# Generated by Django 5.1.7 on 2025-03-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_remove_chamado_analista'),
        ('users', '0004_alter_analista_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('usuario', 'Usuário Comum'), ('analista', 'Analista')], default='usuario', max_length=20),
        ),
        migrations.DeleteModel(
            name='Analista',
        ),
    ]
