# Generated by Django 5.1.7 on 2025-04-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_setor_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('deletado', models.BooleanField(default=False)),
            ],
        ),
    ]
