# Generated by Django 5.1.7 on 2025-05-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_links_logo_alter_links_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acesso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
